name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend         # Navigate to the frontend directory
        npm install         # Install dependencies

    - name: Run build
      run: |
        cd frontend         # Navigate to the frontend directory
        npm run build       # Run the build process

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
        
        # Create the SSH directory and set proper permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Add the SSH private key
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

        # Disable host key checking to avoid interactive prompts
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

        # Step 1: SSH into the server and navigate to the root directory of the project
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
        cd /var/www/rkshaon.info && 
        git pull origin main && 
        cd frontend && 
        npm install && 
        npm run build
        "
